source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "just-the-docs", "~> 0.10"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-relative-links", "~> 0.7"
gem "html-proofer", "~> 5.0", group: :test
